# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\";\n\x0cGroupRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x17\n\x0fpassword_phrase\x18\x02 \x01(\t\"c\n\rGroupResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x16\n\x0evalid_password\x18\x02 \x01(\x08\x12\x19\n\x11group_description\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"%\n\x0fGenerateRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"D\n\x10GenerateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\x90\x01\n\x0b\x41uthService\x12\x37\n\nCheckGroup\x12\x12.auth.GroupRequest\x1a\x13.auth.GroupResponse\"\x00\x12H\n\x15GenerateGroupPassword\x12\x15.auth.GenerateRequest\x1a\x16.auth.GenerateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GROUPREQUEST']._serialized_start=20
  _globals['_GROUPREQUEST']._serialized_end=79
  _globals['_GROUPRESPONSE']._serialized_start=81
  _globals['_GROUPRESPONSE']._serialized_end=180
  _globals['_GENERATEREQUEST']._serialized_start=182
  _globals['_GENERATEREQUEST']._serialized_end=219
  _globals['_GENERATERESPONSE']._serialized_start=221
  _globals['_GENERATERESPONSE']._serialized_end=289
  _globals['_AUTHSERVICE']._serialized_start=292
  _globals['_AUTHSERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
