# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auth_pb2 as auth__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckGroup = channel.unary_unary(
                '/auth.AuthService/CheckGroup',
                request_serializer=auth__pb2.GroupRequest.SerializeToString,
                response_deserializer=auth__pb2.GroupResponse.FromString,
                )
        self.GenerateGroupPassword = channel.unary_unary(
                '/auth.AuthService/GenerateGroupPassword',
                request_serializer=auth__pb2.GenerateRequest.SerializeToString,
                response_deserializer=auth__pb2.GenerateResponse.FromString,
                )


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateGroupPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckGroup,
                    request_deserializer=auth__pb2.GroupRequest.FromString,
                    response_serializer=auth__pb2.GroupResponse.SerializeToString,
            ),
            'GenerateGroupPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateGroupPassword,
                    request_deserializer=auth__pb2.GenerateRequest.FromString,
                    response_serializer=auth__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/CheckGroup',
            auth__pb2.GroupRequest.SerializeToString,
            auth__pb2.GroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateGroupPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/auth.AuthService/GenerateGroupPassword',
            auth__pb2.GenerateRequest.SerializeToString,
            auth__pb2.GenerateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
